### ISSUE TITLE
WebRTC API updates

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#135]
There are some WebRTC changes that need to be sorted out. I believe the following are true to the WebRTC v1.0 API:
1. `navigator.getUserMedia()` has been replaced with `navigator.mediaDevices.getUserMedia()`
2. Changing video sources #84 should be achieved with `navigator.mediaDevices.enumerateDevices()` rather than `MediaStreamTrack.getSources()` (https://www.chromestatus.com/feature/4765305641369600)

A good set of up to date samples:
https://webrtc.github.io/samples/

Chromium 49 seems to support most of these so nwjs 0.13 shouldn't have any particular issues.

**Comment by BoatsAreRockable** [comment]
`mediaDevices.enumerateDevices()` works fine in 0.13 but `navigator.mediaDevices.getUserMedia()` is currently behind a Chromium flag.

https://developers.google.com/web/updates/2015/10/media-devices?hl=en

**Comment by BoatsAreRockable** [comment]
I believe `navigator.mediaDevices.getUserMedia()` could be used and we would generally not have to worry about what is and isn't implemented WebRTC wise if we used this polyfill:
https://github.com/webrtc/adapter

**Comment by le717** [comment]
FYI, I was already planning on using the adapter polyfill and was already using it in my draft code. :)

**Comment by BoatsAreRockable** [comment]
Hi @le717,

I was wondering if you have any video resolution / source changing code to share, as I'd like do some work on this while I have more time over the remaining summer break period.

Resolution and source changing are probably the most important features BA is currently lacking and the main things stopping it from being used in a production environment of any level at the moment.

**Comment by le717** [comment]
I should somewhere, let me check.
**Brain dump**
Start with source selection, it will determine your resolutions. Then when that is solid, add predefined resolutions (recommended: 480p, 720p, 1080p). If camera does not support, drop to next lowest until find supported. Finally, after that, _detect_ support resolutions and generate the resolutions from it.

FWIW, I had pretty much all of the code needed, even the resolution detection. It was not on the same branch, but a lot of the code was shared. So when I said I lost it, I _lost_ it. :(

**Comment by le717** [comment]
GOOD NEWS! :D I found ALL the code I thought I lost. A year later. :D

Bad news: it's all in pieces and is not fully wired up. I lack the time to work on it more than I have tonight because of a really big project I'm doing, so I'm doing as you asked and sending it to you. Maybe you can make sense of it and fix it.

Part 1: https://github.com/BoatsAreRockable/Boats-Animator/tree/camera
Part 2: [camera.zip](https://github.com/BoatsAreRockable/Boats-Animator/files/416340/camera.zip)
Part 3: https://github.com/le717/animator/tree/resolution-draft-1

Part 3 seems to be a different implementation method. Part 1 is definitely your best route, as I've already trimmed out dead/flawed methods. The camera-resolutions module works completely. If it needs to be revised, I recommend noting how it works first. All of the code should use the WebRTC-Adapter as mentioned earlier + whatever the newest spec is (IIRC, the spec has changed to a Promise-based API, IDK if that will affect us here). If you have any questions, you can usually find me on Discord or just send me an email via my site and you can get my email and we can communicate there (a chat is probably best, and it goes without saying here will work too).

**Comment by BoatsAreRockable** [comment]
That's fantastic news! :smile: I will get on with trying to make sense of it all.

**Comment by BoatsAreRockable** [comment]
I haven't forgotten about this, it's that I've been far busier than expected preparing for university!

**Comment by BoatsAreRockable** [comment]
So I've finally got round to making some progress on this.  So far I have implemented source changing.

**Comment by BoatsAreRockable** [comment]
I am struggling to work out how to detect that resolution testing for a device is complete and that the array containing possible constraints objects for it has been populated, after running `cameraResolutions.get()` in `camera.js` (`getCameraResolutions()` in `camera-resolutions.js`).

I suppose I need to add something like a callback/promise to `cameraResolutions.get()`, however this is proving difficult because `camera-resolutions.js` relies on recursion and event listeners as part of its tests.

**Comment by le717** [comment]
Do you still need help with this? I have some free time today and was planning on looking at all this today.

**Comment by BoatsAreRockable** [comment]
@le717 I managed to fully implement resolution testing yesterday, although I still need to do a bit more testing, code style/tidying up, css things and add a few minor features like displaying a camera loading message before I create a pull request.

However, I would still really welcome your feedback on what I've done so far. I feel there must of been a better way of implementing some of what I have done!

**Comment by charlielee** [comment]
Implemented in PR #211 😄 Although, 2 years on further WebRTC changes may be required.
