### ISSUE TITLE
I cant export the files or use camera resolution

### ISSUE THREAD

**Issue by svr82** [charlielee/boats-animator#220]
I need help, I cant not use export files to mp4
I cant not use the camera resolution.

Can you fix this problem now at the moment.

I need this program, I had looking for a animations program over the whole place, on the internet without result, 

please fix the camera resolution and export the files to mp4, exi and so on.

**Comment by le717** [comment]
All of these features are currently being planned and some are in partial development already. We have been extremely busy (at least I have) and have had no time to work on features. Writing software takes a lot of time and effort. It cannot be done in the snap of a finger, unfortunately.

I'm going to close this because, as I said, we are already planning all that, but it doesn't mean you're feedback isn't heard. Thank you for asking! It's good to know that there are people who are interested in Boats Animator! Perhaps in the not too distant future these features will be available for you to use. :)

**Comment by charlielee** [comment]
Thank you for your feedback svr82, I have also just replied to your email. Some other programs you could look at in the meantime are [Heron Animation](https://heronanimation.brunolefevre.net/) or [AnimaShooter Junior](http://www.animashooter.com/).
