### ISSUE TITLE
Open a New Take Option - {Until Full Project System}

### ISSUE THREAD

**Issue by AndreasDemenagas** [charlielee/boats-animator#266]
Currently Boats Animator only allows for one take at a time, thus requiring to restart the program every time someone needs to create a new take. 

A workaround solution, until the full project system suggested in #86 is implemented, would be to allow users to open a new take by clicking a menu bar button. This would simply remove all captured frames from the timeline - thus being able to start a "new take". 

There are a couple of issues that need to be addressed however: 

- Obviously, removing all captured frames - and starting again - would override the ones already captured in the working directory. This can be fixed by suggesting the users to change the working directory - or use the video export feature from #258. (This way the user's captured frames will not be lost or overridden.)

**Comment by charlielee** [comment]
I think it would be better to create a new directory for each take rather than asking the user to change working directory when "New take" is pressed. I really don't like the current warning message, so hopefully we can get rid of it! Plus this starts moving things in the right direction for #86. 🙂  I propose adding the following logic:

* On start up the user selects working directory as usual or the previous working directory used.
* Then the application creates a **directory** at `<working_directory>/TakeXXXX.batake` (eg `Take0001.batake`). The take number is calculated by incrementing by one the id of the last subdirectory with this naming scheme in the working directory.
* This then populates the `Take.takeNumber` variable.

A few other changes should be made:

* The file names of captured frames should also contain the take number eg: `take_0001_frame_0001.png`
* Some check needs to be made that the current working directory isn't set to a .batake directory (hide them from the folder picker somehow or traverse up the folder tree?)
* The confirmTake function needs changing to use the new frame naming scheme
* A "New take" menu option with whatever logic is required to "clear" the timeline/frame reel
* The current take number should be displayed in the status bar `Take 0001`

Once all of this in place we will be quite ready to implement the project system! :)

**Comment by charlielee** [comment]
This stop gap would actually be very easy to implement. We can literally use Electron's refresh window function.

Since this issue was created, the app uses a unique id for frames on each launch so the previous concerns of frames being overwritten are no longer relevant

**Comment by charlielee** [comment]
Closing this issue because I tend to fully support projects in v1.0
