### ISSUE TITLE
Exporting failed

### ISSUE THREAD

**Issue by 3miner6379** [charlielee/boats-animator#290]
i was using this program on Linux.  and when i exported my animation. the output video just cuts outs. it only happed to 2 of my animations to which i worked hours on.

**Comment by charlielee** [comment]
Hi @3miner6379 thanks for reporting this. Which version of the app are you using? Your issue is probably related to issue #289 which I am currently looking into.

The frames of your of animation should be saved as images still in your chosen export directory, so you should be able to create them into an video still using a tool like ffmpeg or a video editor.

**Comment by charlielee** [comment]
@3miner6379 I've just released v0.11.1 which should fix this problem. Feel free to let me know if this is still a problem. 🙂 

https://github.com/charlielee/boats-animator/releases/tag/v0.11.1
