### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by rioforce** [charlielee/boats-animator#35]
I'm sure this will be long in the future of Boats Animator, but I thought I'd mention it now anyway. In short, I'd like theme support. I've been thinking a lot on how to do this, and here's my solution:

-For your program CSS, you'll have to do a bit of re-working. You'll have your normal `style.css` witch has positioning and all (but not colors), but you'll also have a `default-theme.css` that contains ONLY colors. This will be compiled into the program and cannot be directly edited by the end-user.

-You have a folder called `Themes` which the user can view and edit. Inside this folder is a template, which is basically a duplicate of `default-theme.css`. The user can make a copy of the template, rename it, and change the colors inside to design their own themes (you could also package a couple themes inside the program itself).
In your code, you would have something that scans the folder on program start and looks for theme files. If they are present, it reads the header of the theme file (mentioned below) to collect the name of the theme. It then lists the themes in the settings menu for the user to change at will. These themes basically just overwrite the default css colors of the program.

Here's an example of what a theme css could look like:

```
/*
---------------
ThemeName: "Example Name"
ThemeAuthor: "Example Author"
---------------
*/

body {
background-color: blue;
}

.sidebar {
color: white;
background-color: black;
}
```

Themes would be great, then we could change between dark themes, light themes, and any theme we want.

**Comment by rioforce** [comment]
I just edited the post, btw

**Comment by BoatsAreRockable** [comment]
It's funny you should mention themes, I was briefly thinking about them myself the other day! I think they would certainly be a worth while feature to eventually have in BA. Obviously there quite a few bigger things to implement first but I will definitely add themes to the future features list I have. :smile:

**Comment by le717** [comment]
I also have some notes (mainly more lower-level code stuff but also UX/UI) on themes I'll eventually post.

**Comment by BoatsAreRockable** [comment]
Obvious theming is still a way off but it would be great if there was eventually a tablet mode theme. This would increase the size of some of the UI elements and remove the hover effects used in the CSS.

**Comment by BoatsAreRockable** [comment]
Another comment:
Using a CSS preprocessor like LESS or SASS seems a good way of eventually implementing themes since they give us the ability to use variables for things such as colours. LESS appears to be easier to implement and is JavaScript based.

A native CSS solution for variables also appears to be in the works although this has only be added to the upcoming Chrome 49 so I suppose it will take a while to trickle down to NW.js

**Comment by le717** [comment]
I personally use Sass (and was eventually going to suggest BA use it as it'd actually make development nicer), but as Sass is Ruby-based (C if you use libsass), LESS might be a better choice. I need to learn LESS anyway. For performance, we could compile BA's LESS (because yes, we would switch to it internally) to CSS and use that in release builds and invoke LESS only when a non-core theme is used.
 
IDK, NW.JS v0.13.0-beta4 has Chrome 48. 48 moved to the beta channel in early December and each version moves up in the channel roughly every six weeks... There might be a shot at NW.js getting Chrome 49, but a preprocessor would be a better idea.

**Comment by charlielee** [comment]
I've been using Sass a lot at work. It would be lovely to have it in this project. Also node sass exists

https://github.com/sass/node-sass/

**Comment by le717** [comment]
Actually, while Sass is indeed nice, you may not need to use it for themes. Have you heard of CSS custom properties? https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

They are _really_ nice. Like, for real, and great for themes. Just override the property values with new color values and everything changes. I've got a [demo project](https://demo.codetri.net/statesboro-unlocked/) that uses them for theming if you want to take a look as well as a couple other sites that do the same.

**Comment by le717** [comment]
I'm going to recommend closing this option. Themes have literally never come up and, considering how much light effects animation, it's doubtful it will ever be needed. It's not like someone would use a light theme to edit like they would in coding. A well-designed app color scheme is really all you need (which Boats mostly already has).

**Comment by charlielee** [comment]
I am happy for this to be closed
