### ISSUE TITLE
D-SLR support

### ISSUE THREAD

**Issue by charlielee** [charlielee/boats-animator#98]
This is a feature that would certainly be very popular with users, although don't worry I'm not suggesting it should be implemented any time soon! I came across this Node.js module today and wondered if it could be eventually used in BA: https://github.com/lwille/node-gphoto2

**Comment by BoatsAreRockable** [comment]
Node-gphoto2 appears to be Mac and Linux only, although I think there is probably some way of getting it on to Windows. All this D-SLR stuff is way beyond my capabilities right now. A potential better way of implementing D-SLR would probably involve using the Canon SDK, C++ and some other node magic. However that would involve me becoming competent in C++ amongst other things.

I'd consider this to be a stretch goal for Boats Animator. Creating a feature rich, free stop motion animation program for webcams already fills a large demand. Unless a competent C++ developer starts contributing **this is unlikely to be implemented**.

Although if I were to find myself in a few years time knowledgeable in how to do this I totally would! :stuck_out_tongue: 

## How to use a D-SLR with Boats Animator
While built in support for D-SLRs is a long way off, a third-party program could be used to make your D-SLR show up as a Webcam and therefore in Boats Animator. I've haven't personally tried these but some examples include:
* [Camtwist](http://camtwiststudio.com/) (free, Mac only)
* [SparkoCam](http://sparkosoft.com/sparkocam-download) (paid, Windows only)

**Comment by rioforce** [comment]
Just wanted to leave a comment here, even though this is unlikely, if we did do this, here's the steps that it would require (for reference):

- Make it where the DSLR can stream into Boats and act as a webcam for live view
- Use some sort of code (WIA maybe) to make the camera actually capture through the shutter (unlike webcams)

I do agree that simply webcam support would be completely awesome, but if in the far far far far far future, we are able to implement this, I'd love to see it done. That being said, let's focus on the fundamentals first. ;)

Also, sorry for my inactivity, haven't had the free time to contribute lately, and haven't had much to do, frankly, because the back end needs to be implemented (I'm no good with back end) for me to style (I'm much better at styling and CSS).

**Comment by BoatsAreRockable** [comment]
**UPDATE:** I may have found something that might make this be viable again:

I've been looking into digiCamControl recently and the more I look at it, the more impressed I am. I have discovered that the program has a few command line utilities that could potentially be put to use and make proper D-SLR support via the main sensor an actual possibility for Boats Animator.

- http://digicamcontrol.com/doc/userguide/cmd


- http://www.digicamcontrol.com/doc/userguide/singlecmd

**Comment by charlielee** [comment]
I'm going to close this issue. While frequently requested, I don't think DSLR support should be a priority for Boats Animator. I haven't come across any cross-platform solution that doesn't just use live view rather than the actual camera sensors. 

Using actual camera vendor APIs, and somehow getting them to interact with Node.js is probably the most realistic solution.

Perhaps this issue can be resurrected in the future. Maybe as a "plugin" to the main program?
